name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ['*.md', '.gitignore', 'AGENTS.md', '.agents/**']
    branches: ['main', 'master']
  push:
    paths-ignore: ['*.md', '.gitignore', 'AGENTS.md', '.agents/**']
    branches: ['main', 'master']

jobs:
  BuildPackage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86, arm]
    steps:
      - name: Checkout services repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v1

      - name: Build the service package (${{ matrix.arch }})
        id: build
        run: |
          git submodule update --init --recursive
          start-sdk init
          make ${{ matrix.arch }}
          PACKAGE_ID=$(yq -oy ".id" manifest.*)
          mv ${PACKAGE_ID}.s9pk ${PACKAGE_ID}-${{ matrix.arch }}.s9pk
          echo "package_id=$PACKAGE_ID" >> $GITHUB_ENV
          echo "package_filename=${PACKAGE_ID}-${{ matrix.arch }}.s9pk" >> $GITHUB_ENV
          printf "\n SHA256SUM: $(sha256sum ${PACKAGE_ID}-${{ matrix.arch }}.s9pk) \n"
        shell: bash

      - name: Upload .s9pk
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.package_filename }}
          path: ./${{ env.package_filename }}
