name: Release Service

on:
  push:
    tags:
      - 'v*.*'
      - 'v*.*.*'

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v1

      - name: Checkout services repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build the service packages
        run: |
          git submodule update --init --recursive
          start-sdk init
          
          # Build x86
          make x86
          PACKAGE_ID=$(yq -oy ".id" manifest.*)
          mv ${PACKAGE_ID}.s9pk ${PACKAGE_ID}-x86.s9pk
          
          # Clean and build arm
          make clean
          make arm
          mv ${PACKAGE_ID}.s9pk ${PACKAGE_ID}-arm.s9pk
          
          echo "package_id=$PACKAGE_ID" >> $GITHUB_ENV
          echo "package_title=$(yq -oy ".title" manifest.*)" >> $GITHUB_ENV
        shell: bash

      - name: Generate sha256 checksums
        run: |
          PACKAGE_ID=${{ env.package_id }}
          
          printf "\n SHA256SUM x86: $(sha256sum ${PACKAGE_ID}-x86.s9pk) \n"
          sha256sum ${PACKAGE_ID}-x86.s9pk > ${PACKAGE_ID}-x86.s9pk.sha256
          
          printf "\n SHA256SUM arm: $(sha256sum ${PACKAGE_ID}-arm.s9pk) \n"
          sha256sum ${PACKAGE_ID}-arm.s9pk > ${PACKAGE_ID}-arm.s9pk.sha256
        shell: bash

      - name: Generate changelog
        run: |
          PACKAGE_ID=${{ env.package_id }}
          echo "## What's Changed" > change-log.txt
          yq -oy '.release-notes' manifest.* >> change-log.txt
          echo "" >> change-log.txt
          echo "## SHA256 Hashes" >> change-log.txt
          echo '```' >> change-log.txt
          cat ${PACKAGE_ID}-x86.s9pk.sha256 >> change-log.txt
          cat ${PACKAGE_ID}-arm.s9pk.sha256 >> change-log.txt
          echo '```' >> change-log.txt
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.package_title }} ${{ github.ref_name }}
          prerelease: false
          body_path: change-log.txt
          files: |
            ./${{ env.package_id }}-x86.s9pk
            ./${{ env.package_id }}-x86.s9pk.sha256
            ./${{ env.package_id }}-arm.s9pk
            ./${{ env.package_id }}-arm.s9pk.sha256

      - name: Publish to Registry
        env:
          S9USER: ${{ secrets.S9USER }}
          S9PASS: ${{ secrets.S9PASS }}
          S9REGISTRY: ${{ secrets.S9REGISTRY }}
        run: |
          if [[ -z "$S9USER" || -z "$S9PASS" || -z "$S9REGISTRY" ]]; then
            echo "Publish skipped: missing registry credentials."
          else
            start-sdk publish https://$S9USER:$S9PASS@$S9REGISTRY ${{ env.package_id }}-x86.s9pk
            start-sdk publish https://$S9USER:$S9PASS@$S9REGISTRY ${{ env.package_id }}-arm.s9pk
          fi
